PERIODS = 60
ROLLING_PERIODS = 30
SHIFT_PERIODS = 0
TRAILING_DISTANCE_POINTS = 2
PROFIT_THRESHOLD_MULTIPLIER = 35
MARGIN_PERCENT = 0.4
MAX_POSITIONS = 10
MAX_RISK = 0.50
MAX_HALF_LIFE = 1500.0
MAGIC_NUMBER = 345789
TRADING_PAIR_Y = ["WIN*"]
TRADING_PAIR_X = ["WDO*"]
START_TIME_HOUR = 12
START_TIME_MINUTE = 5
TRADE_WINDOW_TIME_HOURS = 7
TRADE_WINDOW_TIME_MINUTES = 30
UNIX_DAY = 24 * 60 * 60
Z_SCORE_ENTRY_THRESHOLD = 0.75
MARGIN_Y = 100
MARGIN_X = 150
VOLUME_FACTOR = 12
FIBO_VOLUME_FACTORS = [1,1,2,3,5,8,13]
PROFIT_THRESHOLD = 0.35
TRAILING_DISTANCE_POINTS = 5
GRID_RANGE = 0.60
MAX_GRIDS = 5
ADDITIONAL_GRID = GRID_RANGE / MAX_GRIDS
NOISE_VARIANCE = 0.004
KALMAN_FILTER_METHOD = True
COINTEGRATION_METHOD = "adf"  # "johansen", "adf", or "engle"
JOHANSEN_CRIT_LEVEL = "95%"        # "90%", "95%", or "99%"
ADF_PVALUE_THRESHOLD = 0.05
ADF_CRIT_LEVEL = "5%"              # "1%", "5%", or "10%"
EG_PVALUE_THRESHOLD = 0.05
EG_CRIT_LEVEL = "5%"               # "1%", "5%", or "10%"
SCAN_COINTEGRATION_METHOD = "adf"  # Applies only to scan_pairs_arbitrage
SCAN_JOHANSEN_CRIT_LEVEL = "95%"        # "90%", "95%", or "99%"
OU_LAMBDA_MIN = 0.01       # Minimum OU mean-reversion speed λ; below this the spread is near a random walk
VECM_ECT_THRESHOLD = 1.5   # Minimum |VECM ECT z-score| required to open orders
HURST_THRESHOLD = 0.5      # Spread Hurst exponent must be below this (mean-reverting)
WAVELET_LEVEL = 1          # DWT decomposition levels for spread denoising (higher = more smoothing)